name: ff
version: '0.1'
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

library:
  dependencies:
    - aeson
    - bytestring
    - containers
    - crdt
    - directory
    - filepath
    - mtl
    - optparse-applicative
    - stm
    - text
    - time
    - yaml
  source-dirs: lib

executables:
  ff:
    dependencies:
      - bytestring
      - containers
      - crdt
      - directory
      - filepath
      - mtl
      - stm
      - text
      - yaml

      - ff

    main: Main
    other-modules: []
    source-dirs: exe/ff

  ff-qt:
    dependencies:
      - crdt
      - hoppy-runtime
      - qtah
      - stm
      - text

      - ff

    ghc-options: -dynamic -optl-pthread
      # -dynamic -- to find libqtah.so automatically
      # -optl-pthread -- Travis can't find pthread
    main: Main
    other-modules: []
    source-dirs: exe/ff-qt

  ff-wx:
    dependencies:
      - crdt
      - stm
      - text
      - wx

      - ff

    main: Main
    source-dirs: exe/ff-wx

tests:
  test:
    dependencies:
      - containers
      - tasty
      - tasty-hunit

      - ff

    main: Main
    source-dirs: test

  features:
    dependencies:
      - blaze-html
    main: Features.hs

dependencies:
  - base
