name: ff
version: '0.1'
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

library:
  dependencies:
    - aeson
    - bytestring
    - containers
    - crdt
    - directory
    - filepath
    - mtl
    - optparse-applicative
    - stm
    - text
    - time
    - yaml
  source-dirs: lib

executables:
  ff:
    dependencies:
      - bytestring
      - containers
      - crdt
      - directory
      - filepath
      - mtl
      - stm
      - text
      - yaml

      - ff

    main: Main
    other-modules: []
    source-dirs: exe/ff

  ff-qt:
    dependencies:
      - crdt
      - hoppy-runtime
      - qtah
      - stm
      - text

      - ff

    ghc-options: -dynamic  # to find libqtah.so automatically
    main: Main
    other-modules: []
    source-dirs: exe/ff-qt

tests:
  test:
    dependencies:
      - containers
      - tasty
      - tasty-hunit

      - ff

    main: Main
    source-dirs: test

dependencies:
  - base
