name: ff
version: '0.1'
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

library:
  dependencies:
    - aeson
    - bytestring
    - crdt
    - directory
    - filepath
    - mtl
    - optparse-applicative
    - stm
    - text
    - time
  source-dirs: lib

executables:
  ff:
    dependencies:
      - aeson
      - bytestring
      - crdt
      - directory
      - filepath
      - mtl
      - stm
      - text
      - yaml

      - ff

    main: Main
    source-dirs: exe/ff

tests:
  test:
    dependencies:
      - tasty
      - tasty-hunit

      - ff

    main: Main
    source-dirs: test

dependencies:
  - base
  - containers
