resolver: lts-10.3

extra-deps:
  # ff:
    - crdt-6.1
  # ff-gui:
    - git: https://gitlab.com/cblp/qtah.git
      commit: 6c8eb65 # branch 'update', 2018-01-11
      subdirs:
        - qtah
        - qtah-cpp
        - qtah-generator
  # qtah:
    - hoppy-generator-0.3.4
    - hoppy-runtime-0.3.2
    - hoppy-std-0.3.0
