resolver: lts-10.3

extra-deps:
  # ff:
    - crdt-6.1
  # ff-qt:
    - git: https://gitlab.com/cblp/qtah.git
      commit: 913d45b  # master, 2018-01-13
      subdirs:
        - qtah
        - qtah-cpp
        - qtah-generator
    # - ../qtah/qtah
    # - ../qtah/qtah-cpp
    # - ../qtah/qtah-generator
  # ff-wx:
    - wx-0.92.3.0
    - wxc-0.92.3.0
    - wxcore-0.92.3.0
    - wxdirect-0.92.3.0
  # qtah:
    - hoppy-generator-0.3.4
    - hoppy-runtime-0.3.2
    - hoppy-std-0.3.0
